// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pipewire.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `pipewire_thread`, `require_pipewire_thread`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<void> pipewireSendMsg({required PipeWireMsg msg}) =>
    RustLib.instance.api.crateApiPipewirePipewireSendMsg(msg: msg);

List<GlobalObject> pipewireGetGlobals() =>
    RustLib.instance.api.crateApiPipewirePipewireGetGlobals();

class GlobalObject {
  final int id;
  final ObjectType kind;
  final int version;
  final Map<String, String> props;

  const GlobalObject({
    required this.id,
    required this.kind,
    required this.version,
    required this.props,
  });

  @override
  int get hashCode =>
      id.hashCode ^ kind.hashCode ^ version.hashCode ^ props.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalObject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          version == other.version &&
          props == other.props;
}

@freezed
sealed class ObjectType with _$ObjectType {
  const ObjectType._();

  const factory ObjectType.client() = ObjectType_Client;
  const factory ObjectType.clientEndpoint() = ObjectType_ClientEndpoint;
  const factory ObjectType.clientNode() = ObjectType_ClientNode;
  const factory ObjectType.clientSession() = ObjectType_ClientSession;
  const factory ObjectType.core() = ObjectType_Core;
  const factory ObjectType.device() = ObjectType_Device;
  const factory ObjectType.endpoint() = ObjectType_Endpoint;
  const factory ObjectType.endpointLink() = ObjectType_EndpointLink;
  const factory ObjectType.endpointStream() = ObjectType_EndpointStream;
  const factory ObjectType.factory_() = ObjectType_Factory;
  const factory ObjectType.link() = ObjectType_Link;
  const factory ObjectType.metadata() = ObjectType_Metadata;
  const factory ObjectType.module() = ObjectType_Module;
  const factory ObjectType.node() = ObjectType_Node;
  const factory ObjectType.port() = ObjectType_Port;
  const factory ObjectType.profiler() = ObjectType_Profiler;
  const factory ObjectType.registry() = ObjectType_Registry;
  const factory ObjectType.session() = ObjectType_Session;
  const factory ObjectType.other(
    String field0,
  ) = ObjectType_Other;
}

enum PipeWireMsg {
  print,
  ;
}
